#@servername =  http://localhost:3100
@servername =  http://117.54.7.227/arov2/api/

### Test Ping
GET {{servername}}/ping HTTP/1.1

### Test accountadd/create
POST {{servername}}/gl/params/journaltype/edit/create HTTP/1.1
Content-Type: application/json

{
 	"jrtype" : "JU",
	"description": "Jurnal Umum2",
	"isactive" : false,
	"validstate" : 0
}

### Test create
POST {{servername}}/gl/params/journaltype/edit/create HTTP/1.1
Content-Type: application/json

{
 	"jrtype" : "JTT",
	"description": "Jurnal Tarikan Tunai2",
	"isactive" : true,
	"validstate" : 0,
	"lang": "id"
}

### Test create
POST {{servername}}/gl/params/journaltype/edit/create HTTP/1.1
Content-Type: application/json

{
 	"jrtype" : "JST",
	"description": "Jurnal Setoran Tunai2",
	"isactive" : true,
	"validstate" : 0,
	"lang": "id"
}


### Test validate
POST {{servername}}/gl/params/journaltype/edit/validation HTTP/1.1
Content-Type: application/json

{
 	"trxid" : "bvsudnm20djgd43lf3mg",
	"validstate" : 1,
	"lang" : "id"
}

### Test List
GET {{servername}}/gl/params/journaltype/list HTTP/1.1

### Test Edit List
GET {{servername}}/gl/params/journaltype/edit/list HTTP/1.1
